## Imports

In [103]:
import pandas as pd

## Read Dataset

In [104]:
data = pd.read_csv("data/fragilidade_cleaned.csv")
data.head(20)

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,...,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100
0,19,1,Joane,2021-11-16,1941-08-20,80.0,F,Água,2.0,153.0,...,1.0,1.0,0.0,16.0,1.0,1.0,1.0,1.0,2.0,80.0
1,19,3,Joane,2022-11-16,1941-08-20,81.0,F,Água,2.0,152.0,...,1.0,1.0,0.0,20.0,2.0,2.0,2.0,2.0,1.0,80.0
2,19,4,Joane,2023-06-20,1941-08-20,81.0,F,Água,2.0,153.0,...,0.0,1.0,0.0,16.0,1.0,1.0,1.0,2.0,1.0,90.0
3,37,1,Joane,2021-11-16,1948-11-20,72.0,F,Água,2.0,149.0,...,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0
4,37,2,Joane,2022-06-29,1948-11-20,73.0,F,Água,2.0,150.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
5,37,3,Joane,2022-11-16,1948-11-20,73.0,F,Água,2.0,148.0,...,1.0,NaN,0.0,NaN,1.0,1.0,1.0,1.0,1.0,70.0
6,37,4,Joane,2023-06-20,1948-11-20,74.0,F,Água,2.0,150.0,...,1.0,1.0,0.0,17.0,1.0,1.0,3.0,1.0,1.0,99.0
7,42,1,Joane,2021-11-16,1939-02-27,82.0,M,Água,2.0,156.0,...,1.0,0.0,0.0,19.0,1.0,1.0,1.0,1.0,1.0,100.0
8,42,2,Joane,2022-06-29,1939-02-27,83.0,M,Água,2.0,154.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
9,42,3,Joane,2022-11-16,1939-02-27,83.0,M,Água,2.0,159.0,...,1.0,1.0,1.0,25.0,1.0,1.0,1.0,1.0,1.0,100.0
10,42,4,Joane,2023-06-20,1939-02-27,84.0,M,Água,2.0,157.0,...,1.0,1.0,1.0,23.0,1.0,1.0,1.0,1.0,1.0,80.0
11,80,2,Joane,2022-06-29,1945-05-21,77.0,F,Água,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
12,80,4,Joane,2023-06-20,1945-05-21,78.0,F,Água,2.0,145.0,...,0.0,1.0,1.0,26.0,3.0,2.0,2.0,3.0,1.0,50.0
13,81,1,Joane,2021-11-16,1953-09-13,68.0,M,Água,2.0,161.0,...,1.0,1.0,1.0,30.0,3.0,1.0,1.0,1.0,2.0,75.0
14,81,2,Joane,2022-06-29,1953-09-13,68.0,M,Água,2.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0
15,81,4,Joane,2023-06-20,1953-09-13,69.0,M,Água,2.0,161.0,...,1.0,1.0,1.0,29.0,1.0,1.0,1.0,1.0,1.0,80.0
16,136,1,Joane,2021-11-16,1950-01-18,71.0,F,Água,2.0,148.0,...,0.0,1.0,1.0,25.0,2.0,1.0,2.0,2.0,2.0,90.0
17,136,2,Joane,2022-06-29,1950-01-18,72.0,F,Água,2.0,148.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0
18,136,4,Joane,2023-06-20,1950-01-18,73.0,F,Água,2.0,148.0,...,1.0,1.0,1.0,27.0,1.0,1.0,1.0,1.0,1.0,70.0
19,182,4,Joane,2023-06-20,1953-03-21,70.0,F,Água,2.0,149.0,...,1.0,1.0,1.0,26.0,1.0,2.0,1.0,3.0,2.0,80.0

## Defining data for testing

In [105]:
data_test = data[data["ID_Aluno"] <= 81]
data_test

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,...,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100
0,19,1,Joane,2021-11-16,1941-08-20,80.0,F,Água,2.0,153.0,...,1.0,1.0,0.0,16.0,1.0,1.0,1.0,1.0,2.0,80.0
1,19,3,Joane,2022-11-16,1941-08-20,81.0,F,Água,2.0,152.0,...,1.0,1.0,0.0,20.0,2.0,2.0,2.0,2.0,1.0,80.0
2,19,4,Joane,2023-06-20,1941-08-20,81.0,F,Água,2.0,153.0,...,0.0,1.0,0.0,16.0,1.0,1.0,1.0,2.0,1.0,90.0
3,37,1,Joane,2021-11-16,1948-11-20,72.0,F,Água,2.0,149.0,...,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0
4,37,2,Joane,2022-06-29,1948-11-20,73.0,F,Água,2.0,150.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
5,37,3,Joane,2022-11-16,1948-11-20,73.0,F,Água,2.0,148.0,...,1.0,NaN,0.0,NaN,1.0,1.0,1.0,1.0,1.0,70.0
6,37,4,Joane,2023-06-20,1948-11-20,74.0,F,Água,2.0,150.0,...,1.0,1.0,0.0,17.0,1.0,1.0,3.0,1.0,1.0,99.0
7,42,1,Joane,2021-11-16,1939-02-27,82.0,M,Água,2.0,156.0,...,1.0,0.0,0.0,19.0,1.0,1.0,1.0,1.0,1.0,100.0
8,42,2,Joane,2022-06-29,1939-02-27,83.0,M,Água,2.0,154.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
9,42,3,Joane,2022-11-16,1939-02-27,83.0,M,Água,2.0,159.0,...,1.0,1.0,1.0,25.0,1.0,1.0,1.0,1.0,1.0,100.0
10,42,4,Joane,2023-06-20,1939-02-27,84.0,M,Água,2.0,157.0,...,1.0,1.0,1.0,23.0,1.0,1.0,1.0,1.0,1.0,80.0
11,80,2,Joane,2022-06-29,1945-05-21,77.0,F,Água,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
12,80,4,Joane,2023-06-20,1945-05-21,78.0,F,Água,2.0,145.0,...,0.0,1.0,1.0,26.0,3.0,2.0,2.0,3.0,1.0,50.0
13,81,1,Joane,2021-11-16,1953-09-13,68.0,M,Água,2.0,161.0,...,1.0,1.0,1.0,30.0,3.0,1.0,1.0,1.0,2.0,75.0
14,81,2,Joane,2022-06-29,1953-09-13,68.0,M,Água,2.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0
15,81,4,Joane,2023-06-20,1953-09-13,69.0,M,Água,2.0,161.0,...,1.0,1.0,1.0,29.0,1.0,1.0,1.0,1.0,1.0,80.0

## Function

In [106]:
import pandas as pd

def filter_data(data: pd.DataFrame, min_instances: int, sequential: bool, aligned: list[int] = None) -> pd.DataFrame:
    """
    Filters users based on number of test instances, sequential constraint, and optional alignment.

    Args:
        data (pd.DataFrame): Dataset with 'ID_Aluno' and 'Momento' columns.
        min_instances (int): Required number of test instances (1–4).
        sequential (bool): If True, instances must form a sequential group (e.g., [1,2,3]).
        aligned (list[int], optional): If provided, user must have exactly these moments. Must match min_instances length.

    Returns:
        pd.DataFrame: Filtered data meeting the criteria.

    Behavior:
        - If aligned is given: selects users matching those moments only.
        - If sequential is True: finds the last available sequential group of min_instances moments.
        - Otherwise: returns last min_instances moments for users with at least that many.
    """
    if aligned:
        if len(aligned) != min_instances:
            raise ValueError("Length of aligned must equal min_instances.")
        if sorted(aligned) != list(range(min(aligned), max(aligned) + 1)) and sequential:
            raise ValueError("Aligned moments are not sequential, so sequential must be False.")

    filtered_rows = []

    for user_id, group in data.groupby("ID_Aluno"):
        momentos = sorted(group["Momento"].unique())

        if len(momentos) < min_instances:
            continue

        if aligned:
            if all(m in momentos for m in aligned):
                filtered_rows.append(group[group["Momento"].isin(aligned)])
        elif sequential:
            # Search for the last sequential block of min_instances
            for i in reversed(range(len(momentos) - min_instances + 1)):
                window = momentos[i:i + min_instances]
                if window == list(range(window[0], window[0] + min_instances)):
                    subset = group[group["Momento"].isin(window)]
                    filtered_rows.append(subset)
                    break
        else:
            # No sequential constraint, just last N
            last_moments = sorted(momentos)[-min_instances:]
            subset = group[group["Momento"].isin(last_moments)]
            filtered_rows.append(subset)

    return pd.concat(filtered_rows, ignore_index=True)

## Testing

In [107]:
data_t = filter_data(data_test, 2, False, [1,2])
data_t

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,...,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100
0,37,1,Joane,2021-11-16,1948-11-20,72.0,F,Água,2.0,149.0,...,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0
1,37,2,Joane,2022-06-29,1948-11-20,73.0,F,Água,2.0,150.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
2,42,1,Joane,2021-11-16,1939-02-27,82.0,M,Água,2.0,156.0,...,1.0,0.0,0.0,19.0,1.0,1.0,1.0,1.0,1.0,100.0
3,42,2,Joane,2022-06-29,1939-02-27,83.0,M,Água,2.0,154.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
4,81,1,Joane,2021-11-16,1953-09-13,68.0,M,Água,2.0,161.0,...,1.0,1.0,1.0,30.0,3.0,1.0,1.0,1.0,2.0,75.0
5,81,2,Joane,2022-06-29,1953-09-13,68.0,M,Água,2.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0

In [108]:
data_t = filter_data(data_test, 2, True)
data_t

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,...,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100
0,19,3,Joane,2022-11-16,1941-08-20,81.0,F,Água,2.0,152.0,...,1.0,1.0,0.0,20.0,2.0,2.0,2.0,2.0,1.0,80.0
1,19,4,Joane,2023-06-20,1941-08-20,81.0,F,Água,2.0,153.0,...,0.0,1.0,0.0,16.0,1.0,1.0,1.0,2.0,1.0,90.0
2,37,3,Joane,2022-11-16,1948-11-20,73.0,F,Água,2.0,148.0,...,1.0,NaN,0.0,NaN,1.0,1.0,1.0,1.0,1.0,70.0
3,37,4,Joane,2023-06-20,1948-11-20,74.0,F,Água,2.0,150.0,...,1.0,1.0,0.0,17.0,1.0,1.0,3.0,1.0,1.0,99.0
4,42,3,Joane,2022-11-16,1939-02-27,83.0,M,Água,2.0,159.0,...,1.0,1.0,1.0,25.0,1.0,1.0,1.0,1.0,1.0,100.0
5,42,4,Joane,2023-06-20,1939-02-27,84.0,M,Água,2.0,157.0,...,1.0,1.0,1.0,23.0,1.0,1.0,1.0,1.0,1.0,80.0
6,81,1,Joane,2021-11-16,1953-09-13,68.0,M,Água,2.0,161.0,...,1.0,1.0,1.0,30.0,3.0,1.0,1.0,1.0,2.0,75.0
7,81,2,Joane,2022-06-29,1953-09-13,68.0,M,Água,2.0,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0

## Filter the data

In [109]:
numer_of_instances = 4          # change this
sequential_instances = True     # change this
alligned_sequence = [1,2,3,4]

filtered_data = filter_data(data, numer_of_instances, sequential_instances, alligned_sequence)

print(filtered_data.shape)
print("This dataset contains", int(filtered_data.shape[0]/numer_of_instances), "different users" )

filtered_data.head(12)

(2172, 85)
This dataset contains 543 different users

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,...,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100
0,37,1,Joane,2021-11-16,1948-11-20,72.0,F,Água,2.0,149.0,...,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0
1,37,2,Joane,2022-06-29,1948-11-20,73.0,F,Água,2.0,150.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
2,37,3,Joane,2022-11-16,1948-11-20,73.0,F,Água,2.0,148.0,...,1.0,NaN,0.0,NaN,1.0,1.0,1.0,1.0,1.0,70.0
3,37,4,Joane,2023-06-20,1948-11-20,74.0,F,Água,2.0,150.0,...,1.0,1.0,0.0,17.0,1.0,1.0,3.0,1.0,1.0,99.0
4,42,1,Joane,2021-11-16,1939-02-27,82.0,M,Água,2.0,156.0,...,1.0,0.0,0.0,19.0,1.0,1.0,1.0,1.0,1.0,100.0
5,42,2,Joane,2022-06-29,1939-02-27,83.0,M,Água,2.0,154.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
6,42,3,Joane,2022-11-16,1939-02-27,83.0,M,Água,2.0,159.0,...,1.0,1.0,1.0,25.0,1.0,1.0,1.0,1.0,1.0,100.0
7,42,4,Joane,2023-06-20,1939-02-27,84.0,M,Água,2.0,157.0,...,1.0,1.0,1.0,23.0,1.0,1.0,1.0,1.0,1.0,80.0
8,593,1,Joane,2021-11-16,1952-11-02,69.0,F,Água,2.0,153.0,...,1.0,1.0,0.0,26.0,1.0,2.0,1.0,1.0,1.0,90.0
9,593,2,Joane,2022-06-29,1952-11-02,69.0,F,Água,2.0,153.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
10,593,3,Joane,2022-11-16,1952-11-02,70.0,F,Água,2.0,152.0,...,1.0,1.0,1.0,NaN,2.0,1.0,1.0,3.0,1.0,90.0
11,593,4,Joane,2023-06-20,1952-11-02,70.0,F,Água,2.0,153.0,...,1.0,1.0,1.0,27.0,1.0,1.0,1.0,1.0,1.0,90.0

## Saving filtered data

In [110]:
#data.to_csv("fragilidade_filtered.csv", index=False)