# Variable Encoding

- **Encode binary variables** - 0/1 
- **Encode ordinal variables** based on their natural order.  
- **Encode nominal variables** with similar techniques.  
- Define a **final encoding function**

## Imports

In [ ]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings("ignore")

## Read dataset
Previously cleaned:
- missing values standardized
- string normalized / typo correction
- outlier removal in mumerical variables

In [2]:
data = pd.read_csv("../data/interim/03. FRAIL_clean_numeric.csv")
data.head()

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,ANTROPOMETRIA_Peso_Kg,Escolaridade,Quedas_ultimos_12meses,Quedas_12meses_Quantas,Quedas_12meses_Situacao,Quedas_12meses_Lesao_Sim_Nao,Quedas_12meses_Lesao_Tipo,Quedas_12meses_Lesao_Local,Quedas_12meses_Assistencia_hospitalar_Sim_Não,Quedas_12meses_Hospitalizado_Sim_Não,Quedas_12meses_Hospitalizado_Dias,Quedas_12meses_Medo_cair_Sim_Não,ATIVIDADE_FISICA_Geral_Sim_Não,ATIVIDADE_FISICA_Caminhada_Frequência_Dias_semana,ATIVIDADE_FISICA_Caminhada_Duracao_min_dia,ATIVIDADE_FISICA_Caminhada_Intensidade,ATIVIDADE_FISICA_Outras_AF_Qual,ATIVIDADE_FISICA_Outras_AF_Frequencia_Dias_semana,ATIVIDADE_FISICA_Outras_AF_Duracao_min_dia,ATIVIDADE_FISICA_Outras_AF_Intensidade,ANTROPOMETRIA_Massa_gorda,ANTROPOMETRIA_Massa_magra_Kg,ANTROPOMETRIA_Gordura_visceral,HANDGRIP_Mao_DOMINANTE,HANDGRIP_DIREITA_tentaiva1,HANDGRIP_DIREITA_tentativa2,HANDGRIP_DIREITA_tentativa_3,HANDGRIP_ESQUERDA_tentativa1,HANDGRIP_ESQUERDA_tentativa2,HANDGRIP_ESQUERDA_tentativa3,TIMED_UP_AND_GO_Simples_tentativa1,TIMED_UP_AND_GO_Simples_tentativa2,Best_TIMED_UP_AND_GO_Simples,Percentil_TIMED_UP_AND_GO_Simples,TIMED_UP_AND_GO_Simples_Apoio_mãos,TIMED_UP_AND_GO_Simples_Auxiliar_marcha,TIMED_UP_AND_GO_Dupla_tarefa_tentativa1,TIMED_UP_AND_GO_Dupla_tarefa_tentativa2,Best_TIMED_UP_AND_GO_Dupla_tarefa,Percentil_TIMED_UP_AND_GO_Dupla_tarefa,TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos,TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha,SIT_TO_STAND_Repetiçoes,Percentil_SIT_TO_STAND_Repetiçoes,SIT_TO_STAND_Apoio_maos,SIT_TO_STAND_Auxiliar_marcha,@6_MIN_ANDAR_Percurso,@6_MIN_ANDAR_N_voltas_completas,@6_MIN_ANDAR_Resultado_teste_Metros,@6_MIN_ANDAR_Distancia_TOTAL_metros,Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros,@6_MIN_ANDAR_Auxiliar_marcha,@6_MIN_ANDAR_Parou,@6_MIN_ANDAR_Parou_Quantas_vezes,@6_MIN_ANDAR_Parou_Motivo,@6_MIN_ANDAR_Desistiu,MMSE_EDUCAÇAO,MMSE_ORIENTACAO_TEMPORAL,MMSE_ORIENTACAO_ESPACIAL,MMSE_RETENCAO,MMSE_ATENCAO_CALCULO,MMSE_EVOCACAO_1,MMSE_LINGUAGEM_A_NOMEACAO,MMSE_LINGUAGEM_B_REPETICAO,MMSE_LINGUAGEM_C_COMANDO,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100,HANDGRIP_DIREITA_tentativa_2
0,19,1,Joane,2021-11-16,1941-08-20,80.0,F,Água,2.0,153.0,59.2,NaN,sim,1.0,caminhar,sim,ferida,joelho,não,não,NaN,sim,sim,6.0,40.0,Moderada,NaN,NaN,NaN,NaN,38.3,25.0,NaN,direita,12.3,12.4,12.0,11.4,12.3,12.6,10.33,11.96,10.33,]50th to 75th],não,não,14.90,13.98,13.98,]25th to 50th],não,não,15.0,]75th to 90th],não,não,A,12.0,0.0,540.0,]90th to 100th],NaN,NaN,NaN,NaN,NaN,Ensino Secundário,3.0,3.0,3.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,16.0,1.0,1.0,1.0,1.0,2.0,80.0,12.0
1,19,3,Joane,2022-11-16,1941-08-20,81.0,F,Água,2.0,152.0,57.7,NaN,sim,1.0,caminhar,sim,NaN,anca,não,NaN,NaN,sim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.4,35.4,10.0,direita,11.2,11.3,12.9,11.9,12.8,11.3,9.24,8.45,8.45,]50th to 75th],não,não,10.83,10.67,10.67,]25th to 50th],não,não,15.0,]75th to 90th],não,não,A,11.0,NaN,495.0,]75th to 90th],não,não,NaN,NaN,NaN,NaN,2.0,2.0,3.0,5.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,20.0,2.0,2.0,2.0,2.0,1.0,80.0,12.9
2,19,4,Joane,2023-06-20,1941-08-20,81.0,F,Água,2.0,153.0,56.3,10º,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.5,35.0,10.0,direita,8.0,8.0,7.0,4.0,3.0,3.0,10.40,9.60,9.60,]50th to 75th],sim,não,16.00,15.00,15.00,]25th to 50th],sim,não,10.5,]50th to 75th],não,NaN,NaN,9.0,20.0,470.0,]75th to 90th],não,não,NaN,NaN,NaN,NaN,2.0,4.0,0.0,4.0,0.0,2.0,1.0,2.0,0.0,1.0,0.0,16.0,1.0,1.0,1.0,2.0,1.0,90.0,7.0
3,37,1,Joane,2021-11-16,1948-11-20,72.0,F,Água,2.0,149.0,81.3,NaN,não,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não,não,0.0,NaN,NaN,NaN,NaN,NaN,NaN,45.7,25.0,NaN,direita,22.2,20.0,22.9,13.2,13.7,18.6,9.08,9.76,9.08,]10th to 25th],não,não,13.79,11.80,11.80,[0 to 10th],não,não,11.0,]10th to 25th],não,não,A,8.0,35.0,395.0,]10th to 25th],NaN,NaN,NaN,NaN,NaN,4ª Classe,0.0,4.0,3.0,5.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0,22.9
4,37,2,Joane,2022-06-29,1948-11-20,73.0,F,Água,2.0,150.0,81.4,NaN,não,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,direita,14.0,17.7,15.7,15.8,17.5,14.9,13.00,14.00,13.00,[0 to 10th],NaN,NaN,15.00,14.00,14.00,[0 to 10th],NaN,NaN,13.0,]25th to 50th],não,não,B,7.0,45.0,395.0,]10th to 25th],não,não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,15.7

## Define different variables

In [3]:
print(len(data.columns))
print(data.columns.to_list())

86
['ID_Aluno', 'Momento', 'Local_de_Avaliacao', 'Data_avaliacao', 'Data_nascimento', 'Age', 'Genero', 'Modalidade', 'Freq_semanal', 'ANTROPOMETRIA_Estatura_cm', 'ANTROPOMETRIA_Peso_Kg', 'Escolaridade', 'Quedas_ultimos_12meses', 'Quedas_12meses_Quantas', 'Quedas_12meses_Situacao', 'Quedas_12meses_Lesao_Sim_Nao', 'Quedas_12meses_Lesao_Tipo', 'Quedas_12meses_Lesao_Local', 'Quedas_12meses_Assistencia_hospitalar_Sim_Não', 'Quedas_12meses_Hospitalizado_Sim_Não', 'Quedas_12meses_Hospitalizado_Dias', 'Quedas_12meses_Medo_cair_Sim_Não', 'ATIVIDADE_FISICA_Geral_Sim_Não', 'ATIVIDADE_FISICA_Caminhada_Frequência_Dias_semana', 'ATIVIDADE_FISICA_Caminhada_Duracao_min_dia', 'ATIVIDADE_FISICA_Caminhada_Intensidade', 'ATIVIDADE_FISICA_Outras_AF_Qual', 'ATIVIDADE_FISICA_Outras_AF_Frequencia_Dias_semana', 'ATIVIDADE_FISICA_Outras_AF_Duracao_min_dia', 'ATIVIDADE_FISICA_Outras_AF_Intensidade', 'ANTROPOMETRIA_Massa_gorda', 'ANTROPOMETRIA_Massa_magra_Kg', 'ANTROPOMETRIA_Gordura_visceral', 'HANDGRIP_Mao_DOMINANTE', 'HANDGRIP_DIREITA_tentaiva1', 'HANDGRIP_DIREITA_tentativa2', 'HANDGRIP_DIREITA_tentativa_3', 'HANDGRIP_ESQUERDA_tentativa1', 'HANDGRIP_ESQUERDA_tentativa2', 'HANDGRIP_ESQUERDA_tentativa3', 'TIMED_UP_AND_GO_Simples_tentativa1', 'TIMED_UP_AND_GO_Simples_tentativa2', 'Best_TIMED_UP_AND_GO_Simples', 'Percentil_TIMED_UP_AND_GO_Simples', 'TIMED_UP_AND_GO_Simples_Apoio_mãos', 'TIMED_UP_AND_GO_Simples_Auxiliar_marcha', 'TIMED_UP_AND_GO_Dupla_tarefa_tentativa1', 'TIMED_UP_AND_GO_Dupla_tarefa_tentativa2', 'Best_TIMED_UP_AND_GO_Dupla_tarefa', 'Percentil_TIMED_UP_AND_GO_Dupla_tarefa', 'TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos', 'TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha', 'SIT_TO_STAND_Repetiçoes', 'Percentil_SIT_TO_STAND_Repetiçoes', 'SIT_TO_STAND_Apoio_maos', 'SIT_TO_STAND_Auxiliar_marcha', '@6_MIN_ANDAR_Percurso', '@6_MIN_ANDAR_N_voltas_completas', '@6_MIN_ANDAR_Resultado_teste_Metros', '@6_MIN_ANDAR_Distancia_TOTAL_metros', 'Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros', '@6_MIN_ANDAR_Auxiliar_marcha', '@6_MIN_ANDAR_Parou', '@6_MIN_ANDAR_Parou_Quantas_vezes', '@6_MIN_ANDAR_Parou_Motivo', '@6_MIN_ANDAR_Desistiu', 'MMSE_EDUCAÇAO', 'MMSE_ORIENTACAO_TEMPORAL', 'MMSE_ORIENTACAO_ESPACIAL', 'MMSE_RETENCAO', 'MMSE_ATENCAO_CALCULO', 'MMSE_EVOCACAO_1', 'MMSE_LINGUAGEM_A_NOMEACAO', 'MMSE_LINGUAGEM_B_REPETICAO', 'MMSE_LINGUAGEM_C_COMANDO', 'MMSE_LINGUAGEM_D_LEITURA', 'MMSE_LINGUAGEM_E_FRASE_ESCRITA', 'MMSE_COPIA_DESENHO_1', 'MMSE_Total', 'EQ5D5L_MOBILIDADE', 'EQ5D5L_CUIDADOS_PESSOAIS', 'EQ5D5L_ATIVIDADES_HABITUAIS', 'EQ5D5L_DOR_MAL_ESTAR', 'EQ5D5L_ANSIEDADE_DEPRESSAO', 'EQ5D5L_A_sua_saude_hoje_0_100', 'HANDGRIP_DIREITA_tentativa_2']

In [4]:
numerical_columns = ["Age", "Freq_semanal", 'ANTROPOMETRIA_Estatura_cm', 'ANTROPOMETRIA_Peso_Kg', 'Quedas_12meses_Quantas', 'Quedas_12meses_Hospitalizado_Dias', 
                     'ATIVIDADE_FISICA_Caminhada_Frequência_Dias_semana', 'ATIVIDADE_FISICA_Caminhada_Duracao_min_dia', 'ATIVIDADE_FISICA_Outras_AF_Frequencia_Dias_semana', 'ATIVIDADE_FISICA_Outras_AF_Duracao_min_dia',
                     'ANTROPOMETRIA_Massa_gorda', 'ANTROPOMETRIA_Massa_magra_Kg', 'ANTROPOMETRIA_Gordura_visceral',
                     'HANDGRIP_DIREITA_tentaiva1', 'HANDGRIP_DIREITA_tentativa2', 'HANDGRIP_DIREITA_tentativa_3',
                     'HANDGRIP_ESQUERDA_tentativa1', 'HANDGRIP_ESQUERDA_tentativa2', 'HANDGRIP_ESQUERDA_tentativa3',
                     'TIMED_UP_AND_GO_Simples_tentativa1', 'TIMED_UP_AND_GO_Simples_tentativa2', 'Best_TIMED_UP_AND_GO_Simples',
                     'TIMED_UP_AND_GO_Dupla_tarefa_tentativa1', 'TIMED_UP_AND_GO_Dupla_tarefa_tentativa2', 'Best_TIMED_UP_AND_GO_Dupla_tarefa',
                     'SIT_TO_STAND_Repetiçoes', 
                     '@6_MIN_ANDAR_N_voltas_completas', '@6_MIN_ANDAR_Resultado_teste_Metros', '@6_MIN_ANDAR_Distancia_TOTAL_metros', '@6_MIN_ANDAR_Parou_Quantas_vezes',
                     'MMSE_ORIENTACAO_TEMPORAL', 'MMSE_ORIENTACAO_ESPACIAL', 'MMSE_RETENCAO', 'MMSE_ATENCAO_CALCULO', 'MMSE_EVOCACAO_1', 'MMSE_LINGUAGEM_A_NOMEACAO', 
                     'MMSE_LINGUAGEM_B_REPETICAO', 'MMSE_LINGUAGEM_C_COMANDO', 'MMSE_LINGUAGEM_D_LEITURA', 'MMSE_LINGUAGEM_E_FRASE_ESCRITA', 'MMSE_COPIA_DESENHO_1', 
                     'MMSE_Total', 'EQ5D5L_MOBILIDADE', 'EQ5D5L_CUIDADOS_PESSOAIS', 'EQ5D5L_ATIVIDADES_HABITUAIS', 'EQ5D5L_DOR_MAL_ESTAR', 'EQ5D5L_ANSIEDADE_DEPRESSAO', 'EQ5D5L_A_sua_saude_hoje_0_100'
                     ]
data[numerical_columns].dtypes

Age                                                  float64
Freq_semanal                                         float64
ANTROPOMETRIA_Estatura_cm                            float64
ANTROPOMETRIA_Peso_Kg                                float64
Quedas_12meses_Quantas                               float64
Quedas_12meses_Hospitalizado_Dias                    float64
ATIVIDADE_FISICA_Caminhada_Frequência_Dias_semana    float64
ATIVIDADE_FISICA_Caminhada_Duracao_min_dia           float64
ATIVIDADE_FISICA_Outras_AF_Frequencia_Dias_semana    float64
ATIVIDADE_FISICA_Outras_AF_Duracao_min_dia           float64
ANTROPOMETRIA_Massa_gorda                            float64
ANTROPOMETRIA_Massa_magra_Kg                         float64
ANTROPOMETRIA_Gordura_visceral                       float64
HANDGRIP_DIREITA_tentaiva1                           float64
HANDGRIP_DIREITA_tentativa2                          float64
HANDGRIP_DIREITA_tentativa_3                         float64
HANDGRIP_ESQUERDA_tentativa1                         float64
HANDGRIP_ESQUERDA_tentativa2                         float64
HANDGRIP_ESQUERDA_tentativa3                         float64
TIMED_UP_AND_GO_Simples_tentativa1                   float64
TIMED_UP_AND_GO_Simples_tentativa2                   float64
Best_TIMED_UP_AND_GO_Simples                         float64
TIMED_UP_AND_GO_Dupla_tarefa_tentativa1              float64
TIMED_UP_AND_GO_Dupla_tarefa_tentativa2              float64
Best_TIMED_UP_AND_GO_Dupla_tarefa                    float64
SIT_TO_STAND_Repetiçoes                              float64
@6_MIN_ANDAR_N_voltas_completas                      float64
@6_MIN_ANDAR_Resultado_teste_Metros                  float64
@6_MIN_ANDAR_Distancia_TOTAL_metros                  float64
@6_MIN_ANDAR_Parou_Quantas_vezes                     float64
MMSE_ORIENTACAO_TEMPORAL                             float64
MMSE_ORIENTACAO_ESPACIAL                             float64
MMSE_RETENCAO                                        float64
MMSE_ATENCAO_CALCULO                                 float64
MMSE_EVOCACAO_1                                      float64
MMSE_LINGUAGEM_A_NOMEACAO                            float64
MMSE_LINGUAGEM_B_REPETICAO                           float64
MMSE_LINGUAGEM_C_COMANDO                             float64
MMSE_LINGUAGEM_D_LEITURA                             float64
MMSE_LINGUAGEM_E_FRASE_ESCRITA                       float64
MMSE_COPIA_DESENHO_1                                 float64
MMSE_Total                                           float64
EQ5D5L_MOBILIDADE                                    float64
EQ5D5L_CUIDADOS_PESSOAIS                             float64
EQ5D5L_ATIVIDADES_HABITUAIS                          float64
EQ5D5L_DOR_MAL_ESTAR                                 float64
EQ5D5L_ANSIEDADE_DEPRESSAO                           float64
EQ5D5L_A_sua_saude_hoje_0_100                        float64
dtype: object

In [5]:
print(len(data.columns.drop(numerical_columns)))
print(data.columns.drop(numerical_columns).to_list())

38
['ID_Aluno', 'Momento', 'Local_de_Avaliacao', 'Data_avaliacao', 'Data_nascimento', 'Genero', 'Modalidade', 'Escolaridade', 'Quedas_ultimos_12meses', 'Quedas_12meses_Situacao', 'Quedas_12meses_Lesao_Sim_Nao', 'Quedas_12meses_Lesao_Tipo', 'Quedas_12meses_Lesao_Local', 'Quedas_12meses_Assistencia_hospitalar_Sim_Não', 'Quedas_12meses_Hospitalizado_Sim_Não', 'Quedas_12meses_Medo_cair_Sim_Não', 'ATIVIDADE_FISICA_Geral_Sim_Não', 'ATIVIDADE_FISICA_Caminhada_Intensidade', 'ATIVIDADE_FISICA_Outras_AF_Qual', 'ATIVIDADE_FISICA_Outras_AF_Intensidade', 'HANDGRIP_Mao_DOMINANTE', 'Percentil_TIMED_UP_AND_GO_Simples', 'TIMED_UP_AND_GO_Simples_Apoio_mãos', 'TIMED_UP_AND_GO_Simples_Auxiliar_marcha', 'Percentil_TIMED_UP_AND_GO_Dupla_tarefa', 'TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos', 'TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha', 'Percentil_SIT_TO_STAND_Repetiçoes', 'SIT_TO_STAND_Apoio_maos', 'SIT_TO_STAND_Auxiliar_marcha', '@6_MIN_ANDAR_Percurso', 'Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros', '@6_MIN_ANDAR_Auxiliar_marcha', '@6_MIN_ANDAR_Parou', '@6_MIN_ANDAR_Parou_Motivo', '@6_MIN_ANDAR_Desistiu', 'MMSE_EDUCAÇAO', 'HANDGRIP_DIREITA_tentativa_2']

In [6]:
binary_columns = ['Genero', 'Quedas_ultimos_12meses', 'Quedas_12meses_Lesao_Sim_Nao', 'Quedas_12meses_Assistencia_hospitalar_Sim_Não', 'Quedas_12meses_Hospitalizado_Sim_Não', 'Quedas_12meses_Medo_cair_Sim_Não',
                  'ATIVIDADE_FISICA_Geral_Sim_Não', 'HANDGRIP_Mao_DOMINANTE', 'TIMED_UP_AND_GO_Simples_Apoio_mãos', 'TIMED_UP_AND_GO_Simples_Auxiliar_marcha', 'TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos',
                  'TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha', 'SIT_TO_STAND_Apoio_maos', 'SIT_TO_STAND_Auxiliar_marcha', '@6_MIN_ANDAR_Auxiliar_marcha', '@6_MIN_ANDAR_Parou'
                  ]
data[binary_columns].dtypes

Genero                                           object
Quedas_ultimos_12meses                           object
Quedas_12meses_Lesao_Sim_Nao                     object
Quedas_12meses_Assistencia_hospitalar_Sim_Não    object
Quedas_12meses_Hospitalizado_Sim_Não             object
Quedas_12meses_Medo_cair_Sim_Não                 object
ATIVIDADE_FISICA_Geral_Sim_Não                   object
HANDGRIP_Mao_DOMINANTE                           object
TIMED_UP_AND_GO_Simples_Apoio_mãos               object
TIMED_UP_AND_GO_Simples_Auxiliar_marcha          object
TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos          object
TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha     object
SIT_TO_STAND_Apoio_maos                          object
SIT_TO_STAND_Auxiliar_marcha                     object
@6_MIN_ANDAR_Auxiliar_marcha                     object
@6_MIN_ANDAR_Parou                               object
dtype: object

In [7]:
print(len(data.columns.drop(numerical_columns).drop(binary_columns)))
print(data.columns.drop(numerical_columns).drop(binary_columns).to_list())

22
['ID_Aluno', 'Momento', 'Local_de_Avaliacao', 'Data_avaliacao', 'Data_nascimento', 'Modalidade', 'Escolaridade', 'Quedas_12meses_Situacao', 'Quedas_12meses_Lesao_Tipo', 'Quedas_12meses_Lesao_Local', 'ATIVIDADE_FISICA_Caminhada_Intensidade', 'ATIVIDADE_FISICA_Outras_AF_Qual', 'ATIVIDADE_FISICA_Outras_AF_Intensidade', 'Percentil_TIMED_UP_AND_GO_Simples', 'Percentil_TIMED_UP_AND_GO_Dupla_tarefa', 'Percentil_SIT_TO_STAND_Repetiçoes', '@6_MIN_ANDAR_Percurso', 'Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros', '@6_MIN_ANDAR_Parou_Motivo', '@6_MIN_ANDAR_Desistiu', 'MMSE_EDUCAÇAO', 'HANDGRIP_DIREITA_tentativa_2']

In [8]:
categorical_ordinal_columns = ['Escolaridade', 'ATIVIDADE_FISICA_Caminhada_Intensidade', 'ATIVIDADE_FISICA_Outras_AF_Intensidade', 'Percentil_TIMED_UP_AND_GO_Simples',
                               'Percentil_TIMED_UP_AND_GO_Dupla_tarefa', 'Percentil_SIT_TO_STAND_Repetiçoes', 'Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros', 'MMSE_EDUCAÇAO'
                               ]
data[categorical_ordinal_columns].dtypes

Escolaridade                                     object
ATIVIDADE_FISICA_Caminhada_Intensidade           object
ATIVIDADE_FISICA_Outras_AF_Intensidade           object
Percentil_TIMED_UP_AND_GO_Simples                object
Percentil_TIMED_UP_AND_GO_Dupla_tarefa           object
Percentil_SIT_TO_STAND_Repetiçoes                object
Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros    object
MMSE_EDUCAÇAO                                    object
dtype: object

In [9]:
print(len(data.columns.drop(numerical_columns).drop(binary_columns).drop(categorical_ordinal_columns)))
print(data.columns.drop(numerical_columns).drop(binary_columns).drop(categorical_ordinal_columns).to_list())

14
['ID_Aluno', 'Momento', 'Local_de_Avaliacao', 'Data_avaliacao', 'Data_nascimento', 'Modalidade', 'Quedas_12meses_Situacao', 'Quedas_12meses_Lesao_Tipo', 'Quedas_12meses_Lesao_Local', 'ATIVIDADE_FISICA_Outras_AF_Qual', '@6_MIN_ANDAR_Percurso', '@6_MIN_ANDAR_Parou_Motivo', '@6_MIN_ANDAR_Desistiu', 'HANDGRIP_DIREITA_tentativa_2']

In [10]:
categorical_columns = ['ID_Aluno', 'Momento', 'Local_de_Avaliacao', 'Modalidade', '@6_MIN_ANDAR_Percurso']
data[categorical_ordinal_columns].dtypes

Escolaridade                                     object
ATIVIDADE_FISICA_Caminhada_Intensidade           object
ATIVIDADE_FISICA_Outras_AF_Intensidade           object
Percentil_TIMED_UP_AND_GO_Simples                object
Percentil_TIMED_UP_AND_GO_Dupla_tarefa           object
Percentil_SIT_TO_STAND_Repetiçoes                object
Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros    object
MMSE_EDUCAÇAO                                    object
dtype: object

In [11]:
embedding_columns = [item for item in data.columns.to_list() if 'pca' in item.lower()]

In [12]:
columns_to_remove = ['Data_avaliacao', 'Data_nascimento']

In [13]:
other_columns = data.columns.drop(numerical_columns).drop(binary_columns).drop(categorical_ordinal_columns).drop(categorical_columns).drop(embedding_columns).drop(columns_to_remove)
other_columns

Index(['Quedas_12meses_Situacao', 'Quedas_12meses_Lesao_Tipo',
       'Quedas_12meses_Lesao_Local', 'ATIVIDADE_FISICA_Outras_AF_Qual',
       '@6_MIN_ANDAR_Parou_Motivo', '@6_MIN_ANDAR_Desistiu',
       'HANDGRIP_DIREITA_tentativa_2'],
      dtype='object')

## Encoding binary columns

In [14]:
binary_columns

['Genero',
 'Quedas_ultimos_12meses',
 'Quedas_12meses_Lesao_Sim_Nao',
 'Quedas_12meses_Assistencia_hospitalar_Sim_Não',
 'Quedas_12meses_Hospitalizado_Sim_Não',
 'Quedas_12meses_Medo_cair_Sim_Não',
 'ATIVIDADE_FISICA_Geral_Sim_Não',
 'HANDGRIP_Mao_DOMINANTE',
 'TIMED_UP_AND_GO_Simples_Apoio_mãos',
 'TIMED_UP_AND_GO_Simples_Auxiliar_marcha',
 'TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos',
 'TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha',
 'SIT_TO_STAND_Apoio_maos',
 'SIT_TO_STAND_Auxiliar_marcha',
 '@6_MIN_ANDAR_Auxiliar_marcha',
 '@6_MIN_ANDAR_Parou']

In [15]:
data.HANDGRIP_Mao_DOMINANTE.value_counts()

HANDGRIP_Mao_DOMINANTE
direita       6306
esquerda       222
ambidestro       1
Name: count, dtype: int64

In [16]:
data["@6_MIN_ANDAR_Desistiu"].value_counts()

@6_MIN_ANDAR_Desistiu
dor na anca                                      4
Não pode caminhar                                3
Dores                                            2
coração                                          2
DOR                                              2
dor no joelho                                    2
DOR NO PÉ (QUEDA NO DIA ANTERIOR)                1
arritmia                                         1
Falta de ar; parada coração; válvula entupida    1
Dor calcanhar                                    1
Dor Joelho                                       1
Falta de ar                                      1
Tonta                                            1
dor nas pernas                                   1
Dor nas Pernas                                   1
cansada                                          1
Não consegue andar bem                           1
Dor na perna                                     1
Próteses bacia e coluna; bronquite               1
cansaço/problemas a respirar                     1
dores na coluna                                  1
dor calcanhar                                    1
Dor virilha                                      1
tonturas                                         1
dor costas e joelho                              1
Dor nas pernas                                   1
cãibra MI esquerdo                               1
Falta Ar                                         1
cansaço                                          1
*Não pode caminhar, lesão joelho direito         1
Dor na anca                                      1
Dor no peito                                     1
Dor nos joelhos e falta de ar                    1
dor na perna/tonturas                            1
dor nos gemeos                                   1
Hérnia                                           1
Dor no femur                                     1
dor joelho                                       1
dor nos joelhos                                  1
DOR NAS PERNAS                                   1
Tonturas. Dores                                  1
DOR NOS OSSOS                                    1
Dor na coluna                                    1
Dor joelho e pé                                  1
cirurgia recente                                 1
Não pode fazer                                   1
falta de ar                                      1
Dor nos Gastrocnémios                            1
Dor Costas e Joelhos                             1
Name: count, dtype: int64

In [17]:
def encode_binary_columns(df):
    # Genero
    df["Genero"] = df["Genero"].replace({"F": 0, "M": 1}).fillna(-1).astype(int)

    # Quedas_ultimos_12meses
    df["Quedas_ultimos_12meses"] = df["Quedas_ultimos_12meses"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # Quedas_12meses_Lesao_Sim_Nao
    df["Quedas_12meses_Lesao_Sim_Nao"] = df["Quedas_12meses_Lesao_Sim_Nao"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # Quedas_12meses_Assistencia_hospitalar_Sim_Não
    df["Quedas_12meses_Assistencia_hospitalar_Sim_Não"] = df["Quedas_12meses_Assistencia_hospitalar_Sim_Não"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # Quedas_12meses_Hospitalizado_Sim_Não
    df["Quedas_12meses_Hospitalizado_Sim_Não"] = df["Quedas_12meses_Hospitalizado_Sim_Não"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # Quedas_12meses_Medo_cair_Sim_Não
    df["Quedas_12meses_Medo_cair_Sim_Não"] = df["Quedas_12meses_Medo_cair_Sim_Não"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # ATIVIDADE_FISICA_Geral_Sim_Não
    df["ATIVIDADE_FISICA_Geral_Sim_Não"] = df["ATIVIDADE_FISICA_Geral_Sim_Não"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # HANDGRIP_Mao_DOMINANTE
    df["HANDGRIP_Mao_DOMINANTE"] = df["HANDGRIP_Mao_DOMINANTE"].replace({"esquerda": 0, "direita": 1, "ambidestro": 1}).fillna(-1).astype(int)

    # TIMED_UP_AND_GO_Simples_Apoio_mãos
    df["TIMED_UP_AND_GO_Simples_Apoio_mãos"] = df["TIMED_UP_AND_GO_Simples_Apoio_mãos"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # TIMED_UP_AND_GO_Simples_Auxiliar_marcha
    df["TIMED_UP_AND_GO_Simples_Auxiliar_marcha"] = df["TIMED_UP_AND_GO_Simples_Auxiliar_marcha"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos
    df["TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos"] = df["TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha
    df["TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha"] = df["TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # SIT_TO_STAND_Apoio_maos
    df["SIT_TO_STAND_Apoio_maos"] = df["SIT_TO_STAND_Apoio_maos"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # SIT_TO_STAND_Auxiliar_marcha
    df["SIT_TO_STAND_Auxiliar_marcha"] = df["SIT_TO_STAND_Auxiliar_marcha"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # @6_MIN_ANDAR_Auxiliar_marcha
    df["@6_MIN_ANDAR_Auxiliar_marcha"] = df["@6_MIN_ANDAR_Auxiliar_marcha"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)

    # @6_MIN_ANDAR_Parou
    df["@6_MIN_ANDAR_Parou"] = df["@6_MIN_ANDAR_Parou"].replace({"não": 0, "sim": 1}).fillna(-1).astype(int)


    return df

In [18]:
data_binary_encoded = encode_binary_columns(data[binary_columns])
data_binary_encoded.head()

,Genero,Quedas_ultimos_12meses,Quedas_12meses_Lesao_Sim_Nao,Quedas_12meses_Assistencia_hospitalar_Sim_Não,Quedas_12meses_Hospitalizado_Sim_Não,Quedas_12meses_Medo_cair_Sim_Não,ATIVIDADE_FISICA_Geral_Sim_Não,HANDGRIP_Mao_DOMINANTE,TIMED_UP_AND_GO_Simples_Apoio_mãos,TIMED_UP_AND_GO_Simples_Auxiliar_marcha,TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos,TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha,SIT_TO_STAND_Apoio_maos,SIT_TO_STAND_Auxiliar_marcha,@6_MIN_ANDAR_Auxiliar_marcha,@6_MIN_ANDAR_Parou
0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,-1,-1
1,0,1,1,0,-1,1,-1,1,0,0,0,0,0,0,0,0
2,0,-1,-1,-1,-1,-1,-1,1,1,0,1,0,0,-1,0,0
3,0,0,-1,-1,-1,0,0,1,0,0,0,0,0,0,-1,-1
4,0,0,-1,-1,-1,0,-1,1,-1,-1,-1,-1,0,0,0,0

## Encoding categorical_ordinal_columns

In [19]:
categorical_ordinal_columns

['Escolaridade',
 'ATIVIDADE_FISICA_Caminhada_Intensidade',
 'ATIVIDADE_FISICA_Outras_AF_Intensidade',
 'Percentil_TIMED_UP_AND_GO_Simples',
 'Percentil_TIMED_UP_AND_GO_Dupla_tarefa',
 'Percentil_SIT_TO_STAND_Repetiçoes',
 'Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros',
 'MMSE_EDUCAÇAO']

In [20]:
data.MMSE_EDUCAÇAO.value_counts()

MMSE_EDUCAÇAO
1º Ciclo                    138
4ª Classe                   117
4º ano                       86
4 Classe                     62
4ª classe                    61
                           ...
3ºCICLO                       1
PROFESSORA LICENCIADA         1
Licenciado                    1
Antigo curso professores      1
Não terminou a escola         1
Name: count, Length: 143, dtype: int64

In [21]:
def encode_categorical_ordinal_columns(df):
    # ATIVIDADE_FISICA_Caminhada_Intensidade
    df["ATIVIDADE_FISICA_Caminhada_Intensidade"] = df["ATIVIDADE_FISICA_Caminhada_Intensidade"].replace({"Baixa": 0, "Moderada": 1, "Elevada": 2}).fillna(-1).astype(int)

    # ATIVIDADE_FISICA_Outras_AF_Intensidade
    df["ATIVIDADE_FISICA_Outras_AF_Intensidade"] = df["ATIVIDADE_FISICA_Outras_AF_Intensidade"].replace({"Baixa": 0, "Moderada": 1, "Elevada": 2}).fillna(-1).astype(int)

    # Percentil_TIMED_UP_AND_GO_Simples
    df["Percentil_TIMED_UP_AND_GO_Simples"] = df["Percentil_TIMED_UP_AND_GO_Simples"].replace({"[0 to 10th]": 0, "]10th to 25th]": 1, "]25th to 50th]": 2,
                                                                                               "]50th to 75th]": 3, "]75th to 90th]": 4, "]90th to 100th]": 5}).fillna(-1).astype(int)
    
    # Percentil_TIMED_UP_AND_GO_Dupla_tarefa
    df["Percentil_TIMED_UP_AND_GO_Dupla_tarefa"] = df["Percentil_TIMED_UP_AND_GO_Dupla_tarefa"].replace({"[0 to 10th]": 0, "]10th to 25th]": 1, "]25th to 50th]": 2,
                                                                                               "]50th to 75th]": 3, "]75th to 90th]": 4, "]90th to 100th]": 5}).fillna(-1).astype(int)

    # Percentil_SIT_TO_STAND_Repetiçoes
    df["Percentil_SIT_TO_STAND_Repetiçoes"] = df["Percentil_SIT_TO_STAND_Repetiçoes"].replace({"[0 to 10th]": 0, "]10th to 25th]": 1, "]25th to 50th]": 2,
                                                                                               "]50th to 75th]": 3, "]75th to 90th]": 4, "]90th to 100th]": 5}).fillna(-1).astype(int)

    # Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros
    df["Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros"] = df["Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros"].replace({"[0 to 10th]": 0, "]10th to 25th]": 1, "]25th to 50th]": 2,
                                                                                               "]50th to 75th]": 3, "]75th to 90th]": 4, "]90th to 100th]": 5}).fillna(-1).astype(int)
    
    # Escolaridade
    df['Escolaridade'] = df['Escolaridade'].str.lower().str.replace(r'[^a-zA-Z0-9áéíóúàèìòùâêîôûãõçÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕÇ]', '', regex=True)
    df['Escolaridade']  = df["Escolaridade"].replace({"sim": -1, "nd": -1,
                                        "não": 0, "nãofrequentou": 0, "nãotem": 0, "analfabeta": 0,
                                        "1classe": 1, "1ano": 1,
                                        "2classe": 2, "2ano": 2,
                                        "3ano": 3, "3classe": 3,
                                        "4classe": 4, "4ano": 4, "1ciclo": 4, "4anoprovadeadmissão": 4,
                                        "5ano": 5, "5classe": 5,
                                        "6ano": 6, "6classe": 6,
                                        "7ano": 7, "7anoantigo": 7,
                                        "8amo": 8, "8ano": 8,
                                        "9ano": 9, "9classe": 9, "3ciclo": 9,
                                        "10ano": 10,
                                        "11ano": 11, "11anosecundário": 11, 
                                        "12ano": 12, "12classe": 12, "9ano12anociteve": 12, "secundário": 12, "5cursoindustrial": 12,
                                        "cursomagistério": 13,
                                        "2anodedireito": 14,
                                        "bacharelato": 15, "bacharlato": 15, 
                                        "licenciatura": 16,
                                        }).fillna(-1).astype(int)
    
    # MMSE_EDUCAÇAO

    df['MMSE_EDUCAÇAO'] = df['MMSE_EDUCAÇAO'].str.lower().str.replace(r'[^a-zA-Z0-9áéíóúàèìòùâêîôûãõçÁÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕÇ]', '', regex=True)
    df['MMSE_EDUCAÇAO'] = df["MMSE_EDUCAÇAO"].replace({"sim": -1, "nd": -1, "semescolaridade": -1, "sescolaridade": -1,
                                            "não": 0, "nãofrequentou": 0, "nãotem": 0, "analfabeta": 0, "analfabeto": 0, "nuncafoiaescola": 0, "nãoandounaescola": 0, "nãoterminouaescola": 0,
                                            "1classe": 1, "1ano": 1,
                                            "2classe": 2, "2ano": 2, "2aclasse": 2,
                                            "3ano": 3, "3classe": 3, "3aclasse": 3,
                                            "4classe": 4, "4ano": 4, "1ciclo": 4, "4anoprovadeadmissão": 4, "4aclasse": 4,
                                            "5ano": 5, "5classe": 5, "5anoantigo": 5,
                                            "6ano": 6, "6classe": 6, "2ciclo":6, "6aclasse": 6, "2anoindustrial": 6,
                                            "7ano": 7, "7anoantigo": 7, "3anocomercial": 7, "3industrialcomercial": 7,
                                            "8amo": 8, "8ano": 8,
                                            "9ano": 9, "9classe": 9, "3ciclo": 9, "9oano": 9, "9anonovasoportunidades": 9, "cursocomercial": 9, "cursodecomércio": 9,
                                            "10ano": 10,
                                            "11ano": 11, "11anosecundário": 11, "4ciclo": 11,
                                            "12ano": 12, "12classe": 12, "9ano12anociteve": 12, "secundário": 12, "5cursoindustrial": 12, "ensinosecundário": 12, "cursoindustrial": 12,
                                            "cursomagistério": 13, "magistérioprofessorprimario": 13, "fezmagistério": 13, "antigocursoprofessores": 13, 
                                            "2anodedireito": 14, "2anofaculdade": 14, "faculdade": 14,
                                            "bacharelato": 15, "bacharlato": 15, "cursosuperiordesecretariado": 15,
                                            "licenciatura": 16, "licenciada": 16, "licenciaturadireito": 16, "professoralicenciada": 16, "licenciado": 16,
                                            "mestrado": 18

                                            }).fillna(-1).astype(int)
    
    return df

In [22]:
data_categorical_ordinal_encoded = encode_categorical_ordinal_columns(data[categorical_ordinal_columns])
data_categorical_ordinal_encoded.head()

,Escolaridade,ATIVIDADE_FISICA_Caminhada_Intensidade,ATIVIDADE_FISICA_Outras_AF_Intensidade,Percentil_TIMED_UP_AND_GO_Simples,Percentil_TIMED_UP_AND_GO_Dupla_tarefa,Percentil_SIT_TO_STAND_Repetiçoes,Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros,MMSE_EDUCAÇAO
0,-1,1,-1,3,2,4,5,12
1,-1,-1,-1,3,2,4,4,-1
2,10,-1,-1,3,2,3,4,-1
3,-1,-1,-1,1,0,1,1,4
4,-1,-1,-1,0,0,2,1,-1

## Encode categorical data

In [23]:
categorical_columns

['ID_Aluno',
 'Momento',
 'Local_de_Avaliacao',
 'Modalidade',
 '@6_MIN_ANDAR_Percurso']

In [24]:
data["@6_MIN_ANDAR_Percurso"].value_counts()

@6_MIN_ANDAR_Percurso
A    4191
B    1546
C     502
F     112
D      90
E       2
Name: count, dtype: int64

In [25]:
def encode_categorical_columns(df):
    # ID_Aluno
    df["ID_Aluno"] = df["ID_Aluno"].fillna(-1).astype(int)

    # Momento
    df["Momento"] = df["Momento"].fillna(-1).astype(int)

    # Local_de_Avaliacao
    df["Local_de_Avaliacao"] = df["Local_de_Avaliacao"].replace({"Famalicão": 0, "Joane": 1, "Ribeirão": 2, "São Mateus": 3}).fillna(-1).astype(int)

    # Modalidade
    df["Modalidade"] = df["Modalidade"].replace({"Terra": 0, "Água": 1, "Água + Terra": 2}).fillna(-1).astype(int)

    # @6_MIN_ANDAR_Percurso
    df["@6_MIN_ANDAR_Percurso"] = df["@6_MIN_ANDAR_Percurso"].replace({"A": 0, "B": 1, "C": 2, "D": 3, "E": 4, "F": 5}).fillna(-1).astype(int)

    return df

In [26]:
data_categorical_encoded = encode_categorical_columns(data[categorical_columns])
data_categorical_encoded.head()

   ID_Aluno  Momento  Local_de_Avaliacao  Modalidade  @6_MIN_ANDAR_Percurso
0        19        1                   1           1                      0
1        19        3                   1           1                      0
2        19        4                   1           1                     -1
3        37        1                   1           1                      0
4        37        2                   1           1                      1

## Encode all data function

In [27]:
data.head()

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,ANTROPOMETRIA_Peso_Kg,Escolaridade,Quedas_ultimos_12meses,Quedas_12meses_Quantas,Quedas_12meses_Situacao,Quedas_12meses_Lesao_Sim_Nao,Quedas_12meses_Lesao_Tipo,Quedas_12meses_Lesao_Local,Quedas_12meses_Assistencia_hospitalar_Sim_Não,Quedas_12meses_Hospitalizado_Sim_Não,Quedas_12meses_Hospitalizado_Dias,Quedas_12meses_Medo_cair_Sim_Não,ATIVIDADE_FISICA_Geral_Sim_Não,ATIVIDADE_FISICA_Caminhada_Frequência_Dias_semana,ATIVIDADE_FISICA_Caminhada_Duracao_min_dia,ATIVIDADE_FISICA_Caminhada_Intensidade,ATIVIDADE_FISICA_Outras_AF_Qual,ATIVIDADE_FISICA_Outras_AF_Frequencia_Dias_semana,ATIVIDADE_FISICA_Outras_AF_Duracao_min_dia,ATIVIDADE_FISICA_Outras_AF_Intensidade,ANTROPOMETRIA_Massa_gorda,ANTROPOMETRIA_Massa_magra_Kg,ANTROPOMETRIA_Gordura_visceral,HANDGRIP_Mao_DOMINANTE,HANDGRIP_DIREITA_tentaiva1,HANDGRIP_DIREITA_tentativa2,HANDGRIP_DIREITA_tentativa_3,HANDGRIP_ESQUERDA_tentativa1,HANDGRIP_ESQUERDA_tentativa2,HANDGRIP_ESQUERDA_tentativa3,TIMED_UP_AND_GO_Simples_tentativa1,TIMED_UP_AND_GO_Simples_tentativa2,Best_TIMED_UP_AND_GO_Simples,Percentil_TIMED_UP_AND_GO_Simples,TIMED_UP_AND_GO_Simples_Apoio_mãos,TIMED_UP_AND_GO_Simples_Auxiliar_marcha,TIMED_UP_AND_GO_Dupla_tarefa_tentativa1,TIMED_UP_AND_GO_Dupla_tarefa_tentativa2,Best_TIMED_UP_AND_GO_Dupla_tarefa,Percentil_TIMED_UP_AND_GO_Dupla_tarefa,TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos,TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha,SIT_TO_STAND_Repetiçoes,Percentil_SIT_TO_STAND_Repetiçoes,SIT_TO_STAND_Apoio_maos,SIT_TO_STAND_Auxiliar_marcha,@6_MIN_ANDAR_Percurso,@6_MIN_ANDAR_N_voltas_completas,@6_MIN_ANDAR_Resultado_teste_Metros,@6_MIN_ANDAR_Distancia_TOTAL_metros,Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros,@6_MIN_ANDAR_Auxiliar_marcha,@6_MIN_ANDAR_Parou,@6_MIN_ANDAR_Parou_Quantas_vezes,@6_MIN_ANDAR_Parou_Motivo,@6_MIN_ANDAR_Desistiu,MMSE_EDUCAÇAO,MMSE_ORIENTACAO_TEMPORAL,MMSE_ORIENTACAO_ESPACIAL,MMSE_RETENCAO,MMSE_ATENCAO_CALCULO,MMSE_EVOCACAO_1,MMSE_LINGUAGEM_A_NOMEACAO,MMSE_LINGUAGEM_B_REPETICAO,MMSE_LINGUAGEM_C_COMANDO,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100,HANDGRIP_DIREITA_tentativa_2
0,19,1,Joane,2021-11-16,1941-08-20,80.0,F,Água,2.0,153.0,59.2,NaN,sim,1.0,caminhar,sim,ferida,joelho,não,não,NaN,sim,sim,6.0,40.0,Moderada,NaN,NaN,NaN,NaN,38.3,25.0,NaN,direita,12.3,12.4,12.0,11.4,12.3,12.6,10.33,11.96,10.33,]50th to 75th],não,não,14.90,13.98,13.98,]25th to 50th],não,não,15.0,]75th to 90th],não,não,A,12.0,0.0,540.0,]90th to 100th],NaN,NaN,NaN,NaN,NaN,Ensino Secundário,3.0,3.0,3.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,16.0,1.0,1.0,1.0,1.0,2.0,80.0,12.0
1,19,3,Joane,2022-11-16,1941-08-20,81.0,F,Água,2.0,152.0,57.7,NaN,sim,1.0,caminhar,sim,NaN,anca,não,NaN,NaN,sim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.4,35.4,10.0,direita,11.2,11.3,12.9,11.9,12.8,11.3,9.24,8.45,8.45,]50th to 75th],não,não,10.83,10.67,10.67,]25th to 50th],não,não,15.0,]75th to 90th],não,não,A,11.0,NaN,495.0,]75th to 90th],não,não,NaN,NaN,NaN,NaN,2.0,2.0,3.0,5.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,20.0,2.0,2.0,2.0,2.0,1.0,80.0,12.9
2,19,4,Joane,2023-06-20,1941-08-20,81.0,F,Água,2.0,153.0,56.3,10º,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.5,35.0,10.0,direita,8.0,8.0,7.0,4.0,3.0,3.0,10.40,9.60,9.60,]50th to 75th],sim,não,16.00,15.00,15.00,]25th to 50th],sim,não,10.5,]50th to 75th],não,NaN,NaN,9.0,20.0,470.0,]75th to 90th],não,não,NaN,NaN,NaN,NaN,2.0,4.0,0.0,4.0,0.0,2.0,1.0,2.0,0.0,1.0,0.0,16.0,1.0,1.0,1.0,2.0,1.0,90.0,7.0
3,37,1,Joane,2021-11-16,1948-11-20,72.0,F,Água,2.0,149.0,81.3,NaN,não,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não,não,0.0,NaN,NaN,NaN,NaN,NaN,NaN,45.7,25.0,NaN,direita,22.2,20.0,22.9,13.2,13.7,18.6,9.08,9.76,9.08,]10th to 25th],não,não,13.79,11.80,11.80,[0 to 10th],não,não,11.0,]10th to 25th],não,não,A,8.0,35.0,395.0,]10th to 25th],NaN,NaN,NaN,NaN,NaN,4ª Classe,0.0,4.0,3.0,5.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0,22.9
4,37,2,Joane,2022-06-29,1948-11-20,73.0,F,Água,2.0,150.0,81.4,NaN,não,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,direita,14.0,17.7,15.7,15.8,17.5,14.9,13.00,14.00,13.00,[0 to 10th],NaN,NaN,15.00,14.00,14.00,[0 to 10th],NaN,NaN,13.0,]25th to 50th],não,não,B,7.0,45.0,395.0,]10th to 25th],não,não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,15.7

In [ ]:
def encode_all_data(df):
    df = encode_binary_columns(df)
    df = encode_categorical_ordinal_columns(df)
    df = encode_categorical_columns(df)

    df = df.fillna(-1)
    df = df.replace({-1: np.nan})


    return df

data = encode_all_data(data)
data.head()

,ID_Aluno,Momento,Local_de_Avaliacao,Data_avaliacao,Data_nascimento,Age,Genero,Modalidade,Freq_semanal,ANTROPOMETRIA_Estatura_cm,ANTROPOMETRIA_Peso_Kg,Escolaridade,Quedas_ultimos_12meses,Quedas_12meses_Quantas,Quedas_12meses_Situacao,Quedas_12meses_Lesao_Sim_Nao,Quedas_12meses_Lesao_Tipo,Quedas_12meses_Lesao_Local,Quedas_12meses_Assistencia_hospitalar_Sim_Não,Quedas_12meses_Hospitalizado_Sim_Não,Quedas_12meses_Hospitalizado_Dias,Quedas_12meses_Medo_cair_Sim_Não,ATIVIDADE_FISICA_Geral_Sim_Não,ATIVIDADE_FISICA_Caminhada_Frequência_Dias_semana,ATIVIDADE_FISICA_Caminhada_Duracao_min_dia,ATIVIDADE_FISICA_Caminhada_Intensidade,ATIVIDADE_FISICA_Outras_AF_Qual,ATIVIDADE_FISICA_Outras_AF_Frequencia_Dias_semana,ATIVIDADE_FISICA_Outras_AF_Duracao_min_dia,ATIVIDADE_FISICA_Outras_AF_Intensidade,ANTROPOMETRIA_Massa_gorda,ANTROPOMETRIA_Massa_magra_Kg,ANTROPOMETRIA_Gordura_visceral,HANDGRIP_Mao_DOMINANTE,HANDGRIP_DIREITA_tentaiva1,HANDGRIP_DIREITA_tentativa2,HANDGRIP_DIREITA_tentativa_3,HANDGRIP_ESQUERDA_tentativa1,HANDGRIP_ESQUERDA_tentativa2,HANDGRIP_ESQUERDA_tentativa3,TIMED_UP_AND_GO_Simples_tentativa1,TIMED_UP_AND_GO_Simples_tentativa2,Best_TIMED_UP_AND_GO_Simples,Percentil_TIMED_UP_AND_GO_Simples,TIMED_UP_AND_GO_Simples_Apoio_mãos,TIMED_UP_AND_GO_Simples_Auxiliar_marcha,TIMED_UP_AND_GO_Dupla_tarefa_tentativa1,TIMED_UP_AND_GO_Dupla_tarefa_tentativa2,Best_TIMED_UP_AND_GO_Dupla_tarefa,Percentil_TIMED_UP_AND_GO_Dupla_tarefa,TIMED_UP_AND_GO_Dupla_tarefa_Apoio_maos,TIMED_UP_AND_GO_Dupla_tarefa_Auxiliar_marcha,SIT_TO_STAND_Repetiçoes,Percentil_SIT_TO_STAND_Repetiçoes,SIT_TO_STAND_Apoio_maos,SIT_TO_STAND_Auxiliar_marcha,@6_MIN_ANDAR_Percurso,@6_MIN_ANDAR_N_voltas_completas,@6_MIN_ANDAR_Resultado_teste_Metros,@6_MIN_ANDAR_Distancia_TOTAL_metros,Percentil_@6_MIN_ANDAR_Distancia_TOTAL_metros,@6_MIN_ANDAR_Auxiliar_marcha,@6_MIN_ANDAR_Parou,@6_MIN_ANDAR_Parou_Quantas_vezes,@6_MIN_ANDAR_Parou_Motivo,@6_MIN_ANDAR_Desistiu,MMSE_EDUCAÇAO,MMSE_ORIENTACAO_TEMPORAL,MMSE_ORIENTACAO_ESPACIAL,MMSE_RETENCAO,MMSE_ATENCAO_CALCULO,MMSE_EVOCACAO_1,MMSE_LINGUAGEM_A_NOMEACAO,MMSE_LINGUAGEM_B_REPETICAO,MMSE_LINGUAGEM_C_COMANDO,MMSE_LINGUAGEM_D_LEITURA,MMSE_LINGUAGEM_E_FRASE_ESCRITA,MMSE_COPIA_DESENHO_1,MMSE_Total,EQ5D5L_MOBILIDADE,EQ5D5L_CUIDADOS_PESSOAIS,EQ5D5L_ATIVIDADES_HABITUAIS,EQ5D5L_DOR_MAL_ESTAR,EQ5D5L_ANSIEDADE_DEPRESSAO,EQ5D5L_A_sua_saude_hoje_0_100,HANDGRIP_DIREITA_tentativa_2
0,19,1,1,2021-11-16,1941-08-20,80.0,0,1.0,2.0,153.0,59.2,NaN,1.0,1.0,caminhar,1.0,ferida,joelho,0.0,0.0,NaN,1.0,1.0,6.0,40.0,1.0,NaN,NaN,NaN,NaN,38.3,25.0,NaN,1.0,12.3,12.4,12.0,11.4,12.3,12.6,10.33,11.96,10.33,3.0,0.0,0.0,14.90,13.98,13.98,2.0,0.0,0.0,15.0,4.0,0.0,0.0,0.0,12.0,0.0,540.0,5.0,NaN,NaN,NaN,NaN,NaN,12.0,3.0,3.0,3.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,16.0,1.0,1.0,1.0,1.0,2.0,80.0,12.0
1,19,3,1,2022-11-16,1941-08-20,81.0,0,1.0,2.0,152.0,57.7,NaN,1.0,1.0,caminhar,1.0,NaN,anca,0.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.4,35.4,10.0,1.0,11.2,11.3,12.9,11.9,12.8,11.3,9.24,8.45,8.45,3.0,0.0,0.0,10.83,10.67,10.67,2.0,0.0,0.0,15.0,4.0,0.0,0.0,0.0,11.0,NaN,495.0,4.0,0.0,0.0,NaN,NaN,NaN,NaN,2.0,2.0,3.0,5.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,20.0,2.0,2.0,2.0,2.0,1.0,80.0,12.9
2,19,4,1,2023-06-20,1941-08-20,81.0,0,1.0,2.0,153.0,56.3,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.5,35.0,10.0,1.0,8.0,8.0,7.0,4.0,3.0,3.0,10.40,9.60,9.60,3.0,1.0,0.0,16.00,15.00,15.00,2.0,1.0,0.0,10.5,3.0,0.0,NaN,NaN,9.0,20.0,470.0,4.0,0.0,0.0,NaN,NaN,NaN,NaN,2.0,4.0,0.0,4.0,0.0,2.0,1.0,2.0,0.0,1.0,0.0,16.0,1.0,1.0,1.0,2.0,1.0,90.0,7.0
3,37,1,1,2021-11-16,1948-11-20,72.0,0,1.0,2.0,149.0,81.3,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,45.7,25.0,NaN,1.0,22.2,20.0,22.9,13.2,13.7,18.6,9.08,9.76,9.08,1.0,0.0,0.0,13.79,11.80,11.80,0.0,0.0,0.0,11.0,1.0,0.0,0.0,0.0,8.0,35.0,395.0,1.0,NaN,NaN,NaN,NaN,NaN,4.0,0.0,4.0,3.0,5.0,0.0,2.0,1.0,3.0,1.0,1.0,0.0,20.0,1.0,1.0,1.0,1.0,2.0,100.0,22.9
4,37,2,1,2022-06-29,1948-11-20,73.0,0,1.0,2.0,150.0,81.4,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,14.0,17.7,15.7,15.8,17.5,14.9,13.00,14.00,13.00,0.0,NaN,NaN,15.00,14.00,14.00,0.0,NaN,NaN,13.0,2.0,0.0,0.0,1.0,7.0,45.0,395.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,15.7

In [29]:
data.dtypes

ID_Aluno                           int32
Momento                            int32
Local_de_Avaliacao                 int32
Data_avaliacao                    object
Data_nascimento                   object
                                  ...
EQ5D5L_ATIVIDADES_HABITUAIS      float64
EQ5D5L_DOR_MAL_ESTAR             float64
EQ5D5L_ANSIEDADE_DEPRESSAO       float64
EQ5D5L_A_sua_saude_hoje_0_100    float64
HANDGRIP_DIREITA_tentativa_2     float64
Length: 86, dtype: object

In [30]:
data.to_csv("../data/interim/04. FRAIL_var_encoded.csv", index=False)